[package]
name = "chevii"
version = "0.1.0"
edition = "2018"

[dependencies]
arrayvec = "0.7.1"
chess = "3.2.0"
env_logger = "0.9.0"
log = "0.4.14"
rand = "0.8.4"
rayon = "1.5.1"
structopt = "0.3.23"
tetra = "0.6.5"

[profile.release]
lto = true
panic = "abort"
debug = true
