[package]
name = "chevii"
version = "0.1.0"
edition = "2018"

[dependencies]
chess = "3.2.0"
env_logger = "0.9.0"
log = "0.4.14"
rayon = "1.5.1"
structopt = "0.3.23"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[profile.release]
lto = true
panic = "abort"
debug = true
